language: generic
jobs:
    include:
      - stage: build docker image
        script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/flightbook-mobileapp .
        - docker images
        - docker tag  $DOCKER_USERNAME/flightbook-mobileapp:latest $DOCKER_USERNAME/flightbook-mobileapp:"$TRAVIS_BUILD_NUMBER"
        - docker push $DOCKER_USERNAME/flightbook-mobileapp:"$TRAVIS_BUILD_NUMBER"
        - docker push $DOCKER_USERNAME/flightbook-mobileapp:latest
    branches:
      only:
      - master